"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { describePatch, errorMessage, rejectionMessage, type ChatReply, type Plan, type PlanKey, type PlanPatch } from "./trail-brief";

type Screen = "home" | "chat" | "review" | "picks" | "shop" | "drop" | "pay" | "tracking" | "profile";
type PayStatus = "idle" | "processing" | "failed";
const DELIVERY_FEE = 9;
const payMethods = [{ id: "apple", label: "Apple Pay", detail: "Touch or Face ID", mark: "" }, { id: "visa", label: "Visa", detail: "Saved card ending 4242", mark: "V" }, { id: "other", label: "Another card", detail: "Add at the partner point", mark: "+" }];
const failureCopy: Record<string, string> = { card_declined: "Your bank declined the charge.", insufficient_funds: "There were not enough funds on the card.", expired_card: "That card has expired.", processing_error: "The payment service could not be reached." };
type Message = { role: "ai" | "user"; text: string };
type Trip = { country: string; city: string; areas: string[]; startDate: string; endDate: string; hotel: string; hotelAddress: string; companions: string; freeTime: string };
type PastTrip = { id: string; city: string; country: string; dates: string; areas: string[]; purchases: string; spend: number; insight: string; color: string };
type PurchaseStatus = "planned" | "bought" | "unavailable" | "skipped";
type Purchase = { status: PurchaseStatus; actualPrice: number; quantity: number; bags: number; handling: "Standard" | "Heavy" | "Fragile" | "Chilled" };
type TransferStatus = "none" | "draft" | "active" | "completed";

const initialPlan: Plan = { recipient: "My mom", quantity: 1, category: "Home & design", budget: 80, preference: "Thoughtful and useful", time: "2 hours", localOnly: true, easyPack: true, hotelDelivery: true };
const initialTrip: Trip = { country: "Canada", city: "Toronto", areas: ["Kensington Market", "Queen West", "Distillery District"], startDate: "2026-08-12", endDate: "2026-08-16", hotel: "The Annex Hotel", hotelAddress: "296 Brunswick Ave", companions: "Solo trip", freeTime: "3 hours" };
const pastTrips: PastTrip[] = [
  { id: "tokyo", city: "Tokyo", country: "Japan", dates: "Apr 3–9, 2025", areas: ["Kichijoji", "Kuramae", "Ginza"], purchases: "Stationery · tea · ceramics", spend: 184, insight: "You chose small, useful objects from independent makers.", color: "peach" },
  { id: "copenhagen", city: "Copenhagen", country: "Denmark", dates: "Sep 12–16, 2024", areas: ["Nørrebro", "Vesterbro"], purchases: "Home design · chocolate", spend: 142, insight: "You preferred local design and paid more for packable quality.", color: "blue" },
];
const starters = [
  { icon: "M", title: "A gift for my mom", prompt: "I want a thoughtful local gift for my mom under CAD 80." },
  { icon: "F", title: "Two equal gifts", prompt: "I need two different but equal-value gifts for my friends." },
  { icon: "T", title: "Treats for my team", prompt: "I need something easy to share with my 12-person lab team." },
];
const productTemplates = [
  { name: "Ontario stoneware tea set", store: "Spacing Store", address: "401 Richmond St W", detour: "+7 min", closes: "Open until 6 PM", confidence: "Recently seen", transfer: "Fragile transfer", color: "peach", mark: "C", reason: "Local maker · fits Mom’s budget", handling: "Fragile" as const },
  { name: "Toronto linen market tote", store: "Kid Icarus", address: "205 Augusta Ave", detour: "+4 min", closes: "Open until 7 PM", confidence: "Call to confirm", transfer: "Standard transfer", color: "blue", mark: "T", reason: "Useful every day · folds flat", handling: "Standard" as const },
  { name: "Maple chocolate collection", store: "Blue Banana", address: "250 Augusta Ave", detour: "+2 min", closes: "Open until 8 PM", confidence: "Recently seen", transfer: "Chilled transfer", color: "yellow", mark: "M", reason: "Local favorite · ice pack ready", handling: "Chilled" as const },
];
const alternativeTemplates = [
  { name: "Hand-thrown espresso pair", store: "Craft Ontario Shop", address: "1106 Queen St W", detour: "+5 min", closes: "Open until 7 PM", confidence: "Sample availability", transfer: "Fragile transfer", color: "yellow", mark: "A", reason: "Nearby alternative · same recipient budget", handling: "Fragile" as const },
  { name: "Toronto risograph zip pouch", store: "Likely General", address: "389 Roncesvalles Ave", detour: "+6 min", closes: "Open until 6 PM", confidence: "Sample availability", transfer: "Standard transfer", color: "peach", mark: "A", reason: "Nearby alternative · useful and packable", handling: "Standard" as const },
  { name: "Ontario berry chocolate box", store: "SOMA Chocolatemaker", address: "32 Tank House Lane", detour: "+3 min", closes: "Open until 8 PM", confidence: "Sample availability", transfer: "Chilled transfer", color: "blue", mark: "A", reason: "Nearby alternative · ice-pack handling", handling: "Chilled" as const },
];

function Brand() { return <div className="brand"><span>T</span><b>TRAIL</b></div>; }
function Header({ title, back, action }: { title?: string; back?: () => void; action?: React.ReactNode }) { return <header className="app-header">{back ? <button className="round-button" onClick={back} aria-label="Go back">←</button> : <Brand />}{title && <b className="header-title">{title}</b>}<div className="header-action">{action}</div></header>; }
function Toggle({ on, onChange, label }: { on: boolean; onChange: (value: boolean) => void; label: string }) { return <button className={on ? "toggle on" : "toggle"} role="switch" aria-checked={on} aria-label={label} onClick={() => onChange(!on)}><i /></button>; }

export default function Home() {
  const [screen, setScreen] = useState<Screen>("home");
  const [trip, setTrip] = useState<Trip>(initialTrip);
  const [areaDraft, setAreaDraft] = useState("");
  const [expandedTrip, setExpandedTrip] = useState<string | null>(null);
  const [plan, setPlan] = useState<Plan>(initialPlan);
  const [approvedPlan, setApprovedPlan] = useState<Plan | null>(null);
  const [messages, setMessages] = useState<Message[]>([{ role: "ai", text: "Hi, I’m Trail. Tell me who you’re shopping for and where today takes you. I’ll find gift stops along your route and get the bags back to your hotel." }]);
  const [input, setInput] = useState("");
  const [thinking, setThinking] = useState(false);
  const [suggestion, setSuggestion] = useState<PlanPatch | null>(null);
  const [deliveryStep, setDeliveryStep] = useState(0);
  const [purchases, setPurchases] = useState<Record<number, Purchase>>({});
  const [editingPurchase, setEditingPurchase] = useState<number | null>(null);
  const [purchaseDraft, setPurchaseDraft] = useState<Purchase | null>(null);
  const [purchaseError, setPurchaseError] = useState("");
  const [routeDirty, setRouteDirty] = useState(false);
  const [shoppingStarted, setShoppingStarted] = useState(false);
  const [transferStatus, setTransferStatus] = useState<TransferStatus>("none");
  const [payMethod, setPayMethod] = useState("apple");
  const [payStatus, setPayStatus] = useState<PayStatus>("idle");
  const [payFailure, setPayFailure] = useState("");
  const [paymentRef, setPaymentRef] = useState("");
  const [forceFail, setForceFail] = useState(false);
  const [selectedBags, setSelectedBags] = useState<Record<number, boolean>>({});
  const [replacementIds, setReplacementIds] = useState<Record<number, boolean>>({});
  const [savedStops, setSavedStops] = useState<Record<number, boolean>>({});
  const [attachmentName, setAttachmentName] = useState("");
  const [toast, setToast] = useState("");
  const [memoryOpen, setMemoryOpen] = useState(false);
  const [memoryEnabled, setMemoryEnabled] = useState(true);
  const [hydrated, setHydrated] = useState(false);

  const estimates = useMemo(() => { const stops = plan.budget < 60 ? 1 : plan.budget < 130 ? 2 : 3; return { stops, minutes: 35 + stops * 22, transfer: plan.hotelDelivery ? 12 : 0 }; }, [plan.budget, plan.hotelDelivery]);
  const activePlan = approvedPlan ?? plan;
  const city = trip.city;
  const products = productTemplates.map((item, index) => ({ ...(replacementIds[index] ? alternativeTemplates[index] : item), area: trip.areas[index % Math.max(1, trip.areas.length)] ?? city, price: Math.max(18, Math.round(activePlan.budget * [.48, .31, .21][index])) }));
  const boughtEntries = Object.entries(purchases).filter(([, purchase]) => purchase.status === "bought");
  const spent = boughtEntries.reduce((sum, [, purchase]) => sum + purchase.actualPrice, 0);
  const bagCount = boughtEntries.reduce((sum, [, purchase]) => sum + purchase.bags, 0);
  const remaining = activePlan.budget - spent;
  const selectedBagCount = boughtEntries.reduce((sum, [key, purchase]) => sum + (selectedBags[Number(key)] ? purchase.bags : 0), 0);
  const go = (next: Screen) => { setScreen(next); window.setTimeout(() => document.querySelector(".screen")?.scrollTo({ top: 0, behavior: "smooth" }), 0); };
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2400); };
  const updatePlan = <K extends keyof Plan>(key: K, value: Plan[K]) => { setPlan((current) => ({ ...current, [key]: value })); if (approvedPlan) setRouteDirty(true); };
  const updateTrip = <K extends keyof Trip>(key: K, value: Trip[K]) => setTrip((current) => ({ ...current, [key]: value }));
  const applyPatch = (patch: PlanPatch) => { if (!patch || !Object.keys(patch).length) return; setPlan((current) => ({ ...current, ...patch })); if (approvedPlan) setRouteDirty(true); };
  const clearFields = (keys: PlanKey[]) => { if (!keys.length) return; setPlan((current) => ({ ...current, ...Object.fromEntries(keys.map((key) => [key, initialPlan[key]])) })); if (approvedPlan) setRouteDirty(true); };
  const acceptSuggestion = () => { if (!suggestion) return; applyPatch(suggestion); setSuggestion(null); notify("Added to your brief"); };
  const sendMessage = async (text: string) => {
    const clean = text.trim(); if (!clean || thinking) return;
    const history = messages.slice(-12);
    setMessages((current) => [...current, { role: "user", text: clean }]); setInput(""); setSuggestion(null); setThinking(true);
    try {
      const response = await fetch("/api/chat", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ message: clean, plan, trip, history }) });
      const data = (await response.json()) as ChatReply & { clear?: PlanKey[] };
      applyPatch(data.patch); clearFields(data.clear ?? []);
      setMessages((current) => [...current, { role: "ai", text: data.reply }]);
      if (data.suggested && Object.keys(data.suggested).length) setSuggestion(data.suggested);
      const rejection = rejectionMessage(data.rejected ?? []);
      if (rejection) setMessages((current) => [...current, { role: "ai", text: rejection }]);
      else if (data.errorCode) notify(errorMessage(data.errorCode));
    } catch {
      setMessages((current) => [...current, { role: "ai", text: "I could not reach Trail AI just now. Your brief is unchanged." }]); notify("Trail AI is offline");
    } finally { setThinking(false); }
  };
  const submit = (event: FormEvent) => { event.preventDefault(); sendMessage(input); };
  const startChat = (prompt?: string) => { go("chat"); if (prompt) window.setTimeout(() => sendMessage(prompt), 50); };
  const addArea = () => { const area = areaDraft.trim(); if (!area || trip.areas.includes(area)) return; updateTrip("areas", [...trip.areas, area]); setAreaDraft(""); notify(`${area} added to this trip`); };
  const purchaseDefaults = (index: number): Purchase => ({ status: "planned", actualPrice: products[index].price, quantity: 1, bags: 1, handling: products[index].handling });
  const setPurchase = (index: number, patch: Partial<Purchase>) => setPurchases((current) => ({ ...current, [index]: { ...purchaseDefaults(index), ...current[index], ...patch } }));
  const openPurchase = (index: number) => { setEditingPurchase(index); setPurchaseDraft(purchases[index] ? { ...purchases[index] } : { status: "bought", actualPrice: products[index].price, quantity: 1, bags: 1, handling: products[index].handling }); setPurchaseError(""); };
  const closePurchase = () => { setEditingPurchase(null); setPurchaseDraft(null); setPurchaseError(""); };
  const confirmPurchase = () => { if (editingPurchase === null || !purchaseDraft) return; if (!Number.isFinite(purchaseDraft.actualPrice) || purchaseDraft.actualPrice <= 0 || purchaseDraft.quantity < 1 || purchaseDraft.bags < 1) { setPurchaseError("Enter a positive total, quantity and bag count."); return; } setPurchases((current) => ({ ...current, [editingPurchase]: { ...purchaseDraft, status: "bought" } })); setSelectedBags((current) => ({ ...current, [editingPurchase]: true })); closePurchase(); notify(`Purchase saved · budget ${activePlan.budget - (spent + purchaseDraft.actualPrice)} CAD`); };
  const replaceStop = (index: number) => { notify("Searching nearby sample stores…"); window.setTimeout(() => { setReplacementIds((current) => ({ ...current, [index]: !current[index] })); setPurchase(index, { status: "planned" }); notify("Nearby alternative added to your route"); }, 650); };
  const openTransfer = () => { const selected = Object.fromEntries(boughtEntries.map(([key]) => [Number(key), true])); setSelectedBags(selected); setTransferStatus("draft"); go("drop"); };
  const shopDestination = () => { if (!approvedPlan || routeDirty) go("review"); else go(shoppingStarted ? "shop" : "picks"); };
  const bagsDestination = () => { if (transferStatus === "active" || transferStatus === "completed") go("tracking"); else if (boughtEntries.length) openTransfer(); else go("tracking"); };
  const payForTransfer = async () => {
    if (payStatus === "processing") return;
    setPayStatus("processing"); setPayFailure("");
    try {
      const response = await fetch("/api/payments/simulate", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ amountCents: DELIVERY_FEE * 100, method: payMethod, outcome: forceFail ? "fail" : "succeed" }) });
      const data = (await response.json()) as { status?: string; failureCode?: string; paymentReference?: string };
      if (data.status !== "captured") { setPayStatus("failed"); setPayFailure(data.failureCode ?? "processing_error"); return; }
      setPaymentRef(data.paymentReference ?? ""); setPayStatus("idle"); setTransferStatus("active"); setDeliveryStep(1); saveDeviceState(); go("tracking"); notify("Delivery paid · simulated");
    } catch {
      setPayStatus("failed"); setPayFailure("processing_error");
    }
  };
  const saveDeviceState = (nextTrip = trip) => { localStorage.setItem("trail-v3-state", JSON.stringify({ trip: nextTrip, plan, approvedPlan, purchases, shoppingStarted, transferStatus, deliveryStep, replacementIds, savedStops, memoryEnabled })); notify("Trip and progress saved on this device"); };
  const attachImage = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setAttachmentName(file.name); setMessages((current) => [...current, { role: "user", text: `Attached reference photo: ${file.name}` }, { role: "ai", text: "I’ll treat this as a visual reference for the shopping brief. The prototype keeps the file on this device and does not upload it." }]); notify("Reference photo attached locally"); };
  useEffect(() => { const timer = window.setTimeout(() => { try { const saved = localStorage.getItem("trail-v3-state"); if (saved) { const state = JSON.parse(saved); if (state.trip) setTrip(state.trip); if (state.plan) setPlan(state.plan); if (state.approvedPlan) setApprovedPlan(state.approvedPlan); if (state.purchases) setPurchases(state.purchases); if (state.shoppingStarted) setShoppingStarted(state.shoppingStarted); if (state.transferStatus) setTransferStatus(state.transferStatus); if (state.deliveryStep) setDeliveryStep(state.deliveryStep); if (state.replacementIds) setReplacementIds(state.replacementIds); if (state.savedStops) setSavedStops(state.savedStops); if (typeof state.memoryEnabled === "boolean") setMemoryEnabled(state.memoryEnabled); } } catch { localStorage.removeItem("trail-v3-state"); } setHydrated(true); }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (!hydrated) return; localStorage.setItem("trail-v3-state", JSON.stringify({ trip, plan, approvedPlan, purchases, shoppingStarted, transferStatus, deliveryStep, replacementIds, savedStops, memoryEnabled })); }, [hydrated, trip, plan, approvedPlan, purchases, shoppingStarted, transferStatus, deliveryStep, replacementIds, savedStops, memoryEnabled]);
  const tripDates = `${new Date(`${trip.startDate}T00:00:00`).toLocaleDateString("en-CA", { month: "short", day: "numeric" })}–${new Date(`${trip.endDate}T00:00:00`).toLocaleDateString("en-CA", { month: "short", day: "numeric" })}`;

  return <main className="stage"><section className="phone" aria-live="polite"><div className="status-bar"><span>9:41</span><div><i /><i /><b /></div></div>
    {screen === "home" && <div className="screen home-screen"><Header action={<button className="avatar" aria-label="Open profile" onClick={() => go("profile")}>SY</button>} />
      <section className="home-hero handsfree-hero"><div className="ai-orbit"><i>✦</i><span>HANDS-FREE SOUVENIR TRAVEL</span></div><p>{city.toUpperCase()} · {trip.freeTime.toUpperCase()} FREE</p><h1>Shop local.<br />Keep your <em>hands free.</em></h1><span>Trail finds gift stops along today’s route. You buy in store—we carry your purchased bags safely to {trip.hotel}.</span></section>
      <button className="journey-card" onClick={() => transferStatus === "active" || transferStatus === "completed" ? go("tracking") : shoppingStarted ? go("shop") : approvedPlan && !routeDirty ? go("picks") : startChat()}><div className="journey-line"><i>YOU</i><span /><i>SHOP</i><span /><i>HOTEL</i></div><div><small>{transferStatus === "active" ? "BAGS ON THE MOVE" : transferStatus === "completed" ? "HOTEL RECEIPT READY" : shoppingStarted ? "CONTINUE TODAY’S ROUTE" : approvedPlan && !routeDirty ? "ROUTE READY" : "PLAN TODAY’S HANDS-FREE ROUTE"}</small><b>{transferStatus === "active" ? "Track purchased bags to your hotel" : transferStatus === "completed" ? "Your bags are waiting at the front desk" : shoppingStarted ? "Continue shopping without losing progress" : approvedPlan && !routeDirty ? "Review your local store stops" : "Find gifts without carrying them all day"}</b><em>{transferStatus === "active" || transferStatus === "completed" ? "Open bag tracking →" : shoppingStarted ? `${boughtEntries.length}/${products.length} stops bought · ${remaining} CAD left →` : "AI picks stores, prices and safe bag transfer →"}</em></div></button>
      <section className="handsfree-proof"><article><i>⌁</i><span><small>ALONG YOUR ROUTE</small><b>3 local stops</b><em>Only +13 min</em></span></article><article><i>▣</i><span><small>TO YOUR HOTEL</small><b>Standard · fragile · chilled</b><em>From CAD $12</em></span></article></section>
      <section className="starter-section"><div className="section-label"><b>What are you looking for?</b><span>Tell Trail naturally</span></div><div className="starter-list">{starters.map((item) => <button key={item.title} onClick={() => startChat(item.prompt)}><i>{item.icon}</i><span><b>{item.title}</b><small>{item.prompt}</small></span><em>›</em></button>)}</div></section>
    </div>}

    {screen === "chat" && <div className="screen chat-screen"><Header title="Ask Trail" back={() => go("home")} action={<button className="text-action" onClick={() => go("review")}>View brief</button>} />
      <div className="chat-status"><i>✦</i><span><b>Trail AI · prototype</b><small>{trip.areas.length} areas · transfer checked after purchase</small></span><em>{memoryEnabled ? "MEMORY ON" : "MEMORY OFF"}</em></div><div className="memory-strip"><span><small>{memoryEnabled ? "TRAIL REMEMBERS" : "TRAIL MEMORY IS OFF"}</small><b>{memoryEnabled ? "Local makers · useful gifts · easy to carry home" : "Recommendations use this trip only"}</b></span><button onClick={() => setMemoryOpen(true)}>Why?</button></div>
      <div className="messages">{messages.map((message, index) => <div className={`message ${message.role}`} key={`${message.role}-${index}`}>{message.role === "ai" && <i>✦</i>}<p>{message.text}</p></div>)}{thinking && <div className="message ai typing"><i>✦</i><p><span /><span /><span /></p></div>}</div>
      {suggestion && <div className="suggestion-chip"><span><small>I UNDERSTOOD</small><b>{describePatch(suggestion).join(" · ")}</b></span><button onClick={acceptSuggestion}>Add to brief</button><button className="ghost" onClick={() => setSuggestion(null)} aria-label="Dismiss suggestion">×</button></div>}<div className="quick-replies"><button onClick={() => sendMessage("Find stores along Kensington and Queen West.")}>Along my route</button><button onClick={() => sendMessage("I want hotel bag transfer for anything heavy, fragile or chilled.")}>Hands-free all day</button><button onClick={() => sendMessage("My total budget is CAD 80.")}>Budget $80</button></div>
      <div className="live-draft"><span><small>SHOPPING BRIEF</small><b>{plan.recipient} · {plan.category}</b></span><strong>${plan.budget}</strong><button onClick={() => go("review")}>Review →</button></div>
      {attachmentName && <div className="attachment-chip">Reference: {attachmentName}<button onClick={() => setAttachmentName("")} aria-label="Remove attachment">×</button></div>}<form className="chat-input" onSubmit={submit}><input id="trail-reference" className="visually-hidden" type="file" accept="image/*" onChange={attachImage} /><button type="button" aria-label="Add reference photo" onClick={() => document.getElementById("trail-reference")?.click()}>＋</button><input value={input} onChange={(event) => setInput(event.target.value)} placeholder="What do you want to bring home?" aria-label="Message Trail" /><button type="submit" aria-label="Send message" disabled={!input.trim() || thinking}>↑</button></form>
      {memoryOpen && <div className="modal-backdrop"><section className="memory-sheet" role="dialog" aria-label="Why Trail remembers"><header><span><small>{memoryEnabled ? "APPROVED TRAVEL MEMORY" : "TRAVEL MEMORY OFF"}</small><b>Why Trail knows this</b></span><button aria-label="Close memory details" onClick={() => setMemoryOpen(false)}>×</button></header><p>{memoryEnabled ? "Tokyo 2025 and Copenhagen 2024 show repeated choices: independent makers, useful objects, and packable quality." : "Trail is not reusing past-trip preferences. Current trip details still shape this shopping route."}</p>{memoryEnabled && <div><span>Local over generic</span><span>Useful over decorative</span><span>Hands-free when helpful</span></div>}<button className="main-button" onClick={() => { setMemoryOpen(false); go("profile"); }}><span>Review trips and memory<small>Edit, enable or forget these preferences</small></span><i>→</i></button></section></div>}
    </div>}

    {screen === "review" && <div className="screen review-screen"><Header title="Shopping brief" back={() => go("chat")} action={<span className="draft-badge">AI DRAFT</span>} /><div className="review-intro"><div className="spark">✦</div><span><p>READY TO REVIEW</p><h1>Gifts, route and<br />hands-free needs.</h1><small>Change any detail. Trail updates store stops and transfer handling.</small></span></div>
      <div className="confidence"><span><b>7 details understood</b><small>Recipient, budget, type, route, time, packing, hotel</small></span><strong>94%</strong></div>
      <section className="settings-card"><label><span><small>SHOPPING FOR</small><input value={plan.recipient} onChange={(e) => updatePlan("recipient", e.target.value)} /></span><i>✎</i></label><label><span><small>NUMBER OF GIFTS</small><input type="number" min="1" max="30" value={plan.quantity} onChange={(e) => updatePlan("quantity", Number(e.target.value))} /></span><i>✎</i></label><label><span><small>GIFT TYPE</small><select value={plan.category} onChange={(e) => updatePlan("category", e.target.value)}><option>Home & design</option><option>Food & treats</option><option>Art & stationery</option><option>Open to ideas</option></select></span><i>⌄</i></label><label><span><small>WHAT IT SHOULD FEEL LIKE</small><select value={plan.preference} onChange={(e) => updatePlan("preference", e.target.value)}><option>Thoughtful and personal</option><option>Thoughtful and useful</option><option>Practical and useful</option><option>Fun and distinctly local</option></select></span><i>⌄</i></label></section>
      <section className="budget-editor"><div><span><small>GIFT BUDGET</small><b>CAD ${plan.budget}</b></span><em>Bag transfer estimated separately</em></div><input type="range" min="40" max="300" step="10" value={plan.budget} onChange={(e) => updatePlan("budget", Number(e.target.value))} /><div className="range-values"><span>$40</span><span>$300</span></div></section>
      <section className="preferences"><div><span><b>Local makers only</b><small>Prioritize Toronto and Canadian brands</small></span><Toggle label="Local makers only" on={plan.localOnly} onChange={(v) => updatePlan("localOnly", v)} /></div><div><span><b>Easy to take home</b><small>Flag heavy, fragile and chilled handling</small></span><Toggle label="Easy to take home" on={plan.easyPack} onChange={(v) => updatePlan("easyPack", v)} /></div><div><span><b>Hands-free hotel transfer</b><small>Carry purchases from partner stores to {trip.hotel}</small></span><Toggle label="Hands-free hotel transfer" on={plan.hotelDelivery} onChange={(v) => updatePlan("hotelDelivery", v)} /></div></section>
      {routeDirty && <div className="route-dirty">Your brief changed. Refresh the route before shopping.</div>}<div className="plan-impact"><div><i>⌁</i><span><small>ROUTE</small><b>{estimates.stops} stores · +13 min</b></span></div><div><i>▣</i><span><small>TRANSFER</small><b>{plan.hotelDelivery ? "Hotel-ready stops" : "Carry purchases"}</b></span></div></div><button className="main-button" onClick={() => { setApprovedPlan({ ...plan }); setRouteDirty(false); setShoppingStarted(false); go("picks"); }}><span>{routeDirty ? "Refresh stores along my route" : "Find stores along my route"}<small>You will buy each item directly in store</small></span><i>→</i></button><button className="back-to-chat" onClick={() => go("chat")}>Keep talking to Trail</button>
    </div>}

    {screen === "picks" && <div className="screen picks-screen"><Header title="Route & stores" back={() => go("review")} action={<button className="text-action" onClick={() => go("review")}>Edit</button>} /><div className="approved-banner"><i>✓</i><span><small>ROUTE READY</small><b>{activePlan.recipient} · CAD ${activePlan.budget} gift budget</b></span></div>
      <div className="result-title"><p>TRAIL’S HANDS-FREE ROUTE · {city.toUpperCase()}</p><h1>Find it locally.<br /><em>Send it ahead.</em></h1><span>Three planned store stops across {trip.areas.join(" → ")}. You buy in person; Trail transfers purchased bags to your hotel.</span></div>
      <div className="result-route"><div><i>YOU</i><span /><i>1</i><span /><i>2</i><span /><i>H</i></div><b>{estimates.minutes} min shopping · only +13 min off today’s route</b><small>Hotel bag transfer supported from all planned stops</small></div>
      <div className="product-list route-product-list">{products.map((item, index) => <article key={`${item.name}-${replacementIds[index] ?? false}`}><div className={`product-art ${item.color}`}>{item.mark}</div><div><small>STOP 0{index + 1} · {item.area.toUpperCase()} · {item.detour}</small><h2>Look for: {item.name}</h2><p><b>{item.store}</b> · {item.address}</p><em>✦ {item.reason}</em><footer><span>{item.closes}</span><span>{item.confidence}</span><span className="transfer-chip">▣ {item.transfer}</span></footer><div className="store-actions"><button onClick={() => { setSavedStops((current) => ({ ...current, [index]: !current[index] })); notify(savedStops[index] ? "Stop removed from your route" : "Stop saved to your route"); }}>{savedStops[index] ? "✓ Saved" : "Save stop"}</button><button onClick={() => window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${item.store} ${item.address} ${city}`)}`, "_blank", "noopener,noreferrer")}>Directions</button><button onClick={() => notify(`Sample contact opened for ${item.store} · confirm availability with the store`)}>Call info</button><button onClick={() => replaceStop(index)}>Replace</button></div></div><strong>${item.price - 6}–{item.price + 6}</strong></article>)}</div>
      <div className="offline-note"><b>You buy in person.</b><span>Prices, availability and route times are sample prototype data. Confirm with the store and pay in person.</span></div><button className="main-button dark" onClick={() => { setShoppingStarted(true); go("shop"); }}><span>Start my hands-free shopping route<small>Visit stores, record purchases, send bags to the hotel</small></span><i>→</i></button>
    </div>}

    {screen === "shop" && <div className="screen shop-screen"><Header title="Shop in store" back={() => go("picks")} action={<span className={`budget-pill ${remaining < 0 ? "over" : ""}`}>{remaining < 0 ? `$${Math.abs(remaining)} over` : `$${remaining} left`}</span>} /><div className="shop-summary"><span><small>TODAY’S ROUTE</small><b>{boughtEntries.length}/{products.length} stops bought</b><em>{bagCount} purchased bag{bagCount === 1 ? "" : "s"} · {trip.freeTime} still out</em></span><strong>${spent}<small>spent</small></strong></div>{remaining < 0 && <div className="budget-warning"><b>CAD ${Math.abs(remaining)} over the gift budget</b><span>Edit a purchase, adjust the budget in your brief, or keep the overage.</span><button onClick={() => go("review")}>Review budget →</button></div>}
      <div className="shop-route-line">{products.map((item, index) => { const status = purchases[index]?.status ?? "planned"; return <article className={status} key={item.name}><i>{status === "bought" ? "✓" : index + 1}</i><div><small>{item.area} · {item.detour}</small><h2>{item.store}</h2><p>Look for {item.name}</p><em>{item.closes} · {item.transfer}</em>{status !== "bought" && <div className="visit-actions"><button onClick={() => openPurchase(index)}>Bought in store</button><button className="secondary" onClick={() => status === "unavailable" ? replaceStop(index) : setPurchase(index, { status: "unavailable" })}>{status === "unavailable" ? "Find nearby alternative" : "Not found"}</button><button className="quiet" onClick={() => { setPurchase(index, { status: status === "skipped" ? "planned" : "skipped" }); notify(status === "skipped" ? "Stop restored" : "Stop skipped · tap Undo to restore"); }}>{status === "skipped" ? "Undo skip" : "Skip"}</button></div>}{status === "bought" && <button className="purchase-receipt" onClick={() => openPurchase(index)}>${purchases[index].actualPrice} total · {purchases[index].bags} bag{purchases[index].bags === 1 ? "" : "s"} · {purchases[index].handling} · Edit</button>}{status === "unavailable" && <p className="alert-copy">Not found. Search a nearby sample store in the same budget.</p>}</div></article>; })}</div>
      {boughtEntries.length > 0 && plan.hotelDelivery && <section className="handsfree-trigger"><div><i>▣</i><span><small>KEEP EXPLORING HANDS-FREE</small><b>{bagCount} bag{bagCount === 1 ? "" : "s"} · {trip.freeTime} left outside</b><em>Handling is checked from your saved purchase details</em></span></div><button onClick={openTransfer} disabled={!trip.hotel.trim()}>Send purchased bags to {trip.hotel || "your hotel"} →</button>{!trip.hotel.trim() && <p>Add a hotel in Trips before requesting transfer.</p>}</section>}
      {editingPurchase !== null && purchaseDraft && <div className="modal-backdrop"><section className="purchase-sheet" role="dialog" aria-label="Record in-store purchase"><header><span><small>{purchases[editingPurchase]?.status === "bought" ? "EDIT PURCHASE" : "BOUGHT IN STORE"}</small><b>{products[editingPurchase].store}</b></span><button aria-label="Cancel purchase record" onClick={closePurchase}>×</button></header><label>Total paid, tax included<input type="number" min="0.01" step="0.01" value={purchaseDraft.actualPrice} onChange={(e) => setPurchaseDraft({ ...purchaseDraft, actualPrice: Number(e.target.value) })} /></label><div className="sheet-pair"><label>Quantity<input type="number" min="1" value={purchaseDraft.quantity} onChange={(e) => setPurchaseDraft({ ...purchaseDraft, quantity: Number(e.target.value) })} /></label><label>Shopping bags<input type="number" min="1" value={purchaseDraft.bags} onChange={(e) => setPurchaseDraft({ ...purchaseDraft, bags: Number(e.target.value) })} /></label></div><label>Handling<select value={purchaseDraft.handling} onChange={(e) => setPurchaseDraft({ ...purchaseDraft, handling: e.target.value as Purchase["handling"] })}><option>Standard</option><option>Heavy</option><option>Fragile</option><option>Chilled</option></select></label><div className="sheet-impact"><span>Gift budget after saving</span><b className={activePlan.budget - (spent - (purchases[editingPurchase]?.actualPrice ?? 0) + purchaseDraft.actualPrice) < 0 ? "negative" : ""}>CAD {activePlan.budget - (spent - (purchases[editingPurchase]?.actualPrice ?? 0) + purchaseDraft.actualPrice)}</b></div>{purchaseError && <p className="form-error">{purchaseError}</p>}<button className="main-button" onClick={confirmPurchase}><span>Save purchase<small>Update budget and bag transfer options</small></span><i>✓</i></button>{purchases[editingPurchase]?.status === "bought" && <button className="refund-button" onClick={() => { setPurchase(editingPurchase, { status: "planned" }); closePurchase(); notify("Purchase removed and budget restored"); }}>Remove purchase / refund</button>}</section></div>}
    </div>}

    {screen === "drop" && <div className="screen drop-screen"><Header title="Hotel bag transfer" back={() => go("shop")} action={<span className="draft-badge">{selectedBagCount} {selectedBagCount === 1 ? "BAG" : "BAGS"}</span>} /><div className="bag-visual"><i>TRAIL</i><i>LOCAL</i><span>✓</span></div><div className="drop-copy"><p>YOUR PURCHASES · YOUR HOTEL</p><h1>Choose the bags.<br /><em>Keep exploring.</em></h1><span>You paid the stores directly. Trail only carries the sealed, purchased bags you select.</span></div>
      <section className="bag-selector"><header><span><small>PURCHASED BAGS</small><b>Select for hotel transfer</b></span><em>{selectedBagCount} selected</em></header>{boughtEntries.map(([key, purchase]) => { const index = Number(key); return <label key={key}><input type="checkbox" checked={Boolean(selectedBags[index])} onChange={(event) => setSelectedBags((current) => ({ ...current, [index]: event.target.checked }))} /><span><b>{products[index].store}</b><small>{purchase.bags} bag{purchase.bags === 1 ? "" : "s"} · {purchase.handling} · CAD ${purchase.actualPrice}</small></span><i>{purchase.handling === "Chilled" ? "❄" : purchase.handling === "Fragile" ? "◇" : "▣"}</i></label>; })}</section>
      <section className="handling-list"><header><span><small>SAMPLE TRANSFER CHECK</small><b>Handling and hotel conditions</b></span><em>{selectedBagCount > 0 && trip.hotel.trim() ? "ELIGIBLE" : "NEEDS INFO"}</em></header><div>{boughtEntries.some(([key, item]) => selectedBags[Number(key)] && item.handling === "Fragile") && <span><i>◇</i><b>Fragile</b><small>Store packing and seal photo required</small></span>}{boughtEntries.some(([key, item]) => selectedBags[Number(key)] && item.handling === "Chilled") && <span><i>❄</i><b>Chilled</b><small>Sample ice-pack window until 7:30 PM</small></span>}<span><i>H</i><b>Hotel</b><small>{trip.hotel ? "Sample front desk acceptance" : "Hotel is missing"}</small></span></div></section>
      <div className="drop-pass"><div><span>SAMPLE BAG TRANSFER PASS</span><b>TR–2718</b></div><div className="barcode" /><small>{trip.hotel} · sample ETA 6:30–7:00 PM · estimated CAD $9</small></div><div className="ownership-note">For items you already bought. TRAIL does not order products from the store. Partner, price and ETA are prototype simulations.</div><button className="main-button dark" disabled={selectedBagCount === 0 || !trip.hotel.trim()} onClick={() => { setPayStatus("idle"); setPayFailure(""); go("pay"); }}><span>Review and pay for delivery<small>{selectedBagCount === 0 ? "Select at least one purchased bag" : `CAD $${DELIVERY_FEE} reserved · nothing charged yet`}</small></span><i>→</i></button>
    </div>}

    {screen === "pay" && <div className="screen pay-screen"><Header title={payStatus === "failed" ? "Payment failed" : "Pay for delivery"} back={() => go("drop")} action={<span className="draft-badge">SIMULATED</span>} />
      {payStatus === "failed" ? <>
        <section className="pay-failed"><i>!</i><b>Payment didn’t go through</b><small>{failureCopy[payFailure] ?? failureCopy.processing_error} Your card wasn’t charged, and the CAD ${DELIVERY_FEE} delivery reserve is still protected.</small></section>
        <button className="main-button" onClick={() => { setPayStatus("idle"); setPayFailure(""); }}><span>Try again<small>Nothing has been charged</small></span><i>↺</i></button>
        <button className="back-to-chat" onClick={() => { setForceFail(false); setPayStatus("idle"); setPayFailure(""); }}>Use a different payment method</button>
        <button className="refund-button" onClick={() => { setPayStatus("idle"); setPayFailure(""); go("drop"); notify("Delivery cancelled · reserve released"); }}>Cancel this delivery</button>
      </> : <>
        <div className="pay-amount"><small>HOTEL BAG DELIVERY</small><b>CAD ${DELIVERY_FEE}.00</b><em>{selectedBagCount || bagCount} {(selectedBagCount || bagCount) === 1 ? "bag" : "bags"} · {trip.hotel || "your hotel"} · sample ETA 6:30–7:00 PM</em></div>
        <section className="pay-methods"><header><small>PAY WITH</small></header>{payMethods.map((method) => <label key={method.id} className={payMethod === method.id ? "on" : ""}><input type="radio" name="pay-method" checked={payMethod === method.id} onChange={() => setPayMethod(method.id)} /><i>{method.mark}</i><span><b>{method.label}</b><small>{method.detail}</small></span></label>)}</section>
        <label className="pay-testing"><input type="checkbox" checked={forceFail} onChange={(event) => setForceFail(event.target.checked)} /><span><b>Test a failed payment</b><small>Runs the decline path instead of a successful charge</small></span></label>
        <div className="ownership-note">No money moves. Trail is simulating the card charge so the delivery flow can be tested end to end.</div>
        <button className="main-button dark" disabled={payStatus === "processing"} onClick={payForTransfer}><span>{payStatus === "processing" ? "Contacting the card…" : `Pay CAD $${DELIVERY_FEE}.00`}<small>{payStatus === "processing" ? "This takes a moment" : "Reserved amount is charged now"}</small></span><i>→</i></button>
      </>}
    </div>}

    {screen === "tracking" && <div className="screen tracking-screen"><Header action={<button className="text-action light" onClick={() => go("home")}>Done</button>} />{bagCount === 0 ? <section className="bags-empty"><i>▣</i><p>HANDS-FREE WHEN YOU NEED IT</p><h1>No purchased bags yet.</h1><span>Visit a recommended store and save an in-store purchase. Then Trail can carry the sealed bag to {trip.hotel}.</span><button onClick={shopDestination}>Go to my shopping route →</button></section> : <><div className="simulation-badge">PROTOTYPE TRANSFER SIMULATION</div><div className="free-hands"><div>✓</div><p>{deliveryStep === 3 ? "SAMPLE HOTEL RECEIPT" : "PURCHASED BAGS ON THE MOVE"}</p><h1>{deliveryStep === 3 ? "Waiting safely at the hotel." : "Your hands are free."}</h1><span>{deliveryStep === 3 ? `The sample front desk at ${trip.hotel} checked every seal.` : "Keep exploring. This prototype lets you preview the transfer states."}</span></div><div className="tracking-card"><div><span>TR–2718 · {selectedBagCount || bagCount} purchased {(selectedBagCount || bagCount) === 1 ? "bag" : "bags"}</span><b>{deliveryStep === 1 ? "Partner handoff" : deliveryStep === 2 ? "On the way" : "Hotel received"}</b></div><section>{["Sealed", "Collected", "On route", "At hotel"].map((label, index) => <span className={index <= deliveryStep ? "done" : ""} key={label}><i>{index < deliveryStep ? "✓" : ""}</i><small>{label}</small></span>)}</section><footer><span>{deliveryStep === 3 ? "Sample hotel receipt" : "Sample ETA"}</span><b>{deliveryStep === 3 ? "Front desk · 6:42 PM" : "6:30–7:00 PM"}</b></footer>{paymentRef && <div className="tracking-payment"><span>Payment</span><b>{paymentRef} · CAD ${DELIVERY_FEE} paid</b></div>}{deliveryStep < 3 && <button onClick={() => { const next = Math.min(3, deliveryStep + 1); setDeliveryStep(next); if (next === 3) { setTransferStatus("completed"); notify("Sample hotel receipt created"); } }}>Preview next status →</button>}{deliveryStep === 3 && <button onClick={() => notify("Hotel receipt saved with bag IDs and seal status")}>Save hotel receipt →</button>}</div>{boughtEntries.some(([key, item]) => selectedBags[Number(key)] && item.handling === "Chilled") && <div className="cold-chain"><i>❄</i><span><b>Chilled handling simulated</b><small>Sample ice-pack window remains safe through handoff</small></span></div>}</>}</div>}

    {screen === "profile" && <div className="screen profile-screen"><Header title="Trips" back={() => go("home")} action={<button className="text-action" onClick={() => { saveDeviceState(); go("home"); }}>Save</button>} /><section className="profile-intro"><div className="profile-mark">SY</div><span><p>SOO’S TRAVEL MEMORY</p><h1>{city}<br /><em>{tripDates}</em></h1><small>Plan routes, send purchases to your hotel, and reuse what Trail learns.</small></span></section><section className="trip-card"><header><span><small>CURRENT TRIP</small><b>{trip.city}, {trip.country}</b></span><i>⌖</i></header><div className="trip-area-preview">{trip.areas.map((area) => <span key={area}>{area}</span>)}</div><footer><span>{trip.companions}</span><b>{trip.freeTime} to shop</b></footer></section>
      <section className="ai-memory-card"><header><i>✦</i><span><small>{memoryEnabled ? "APPROVED TRAIL MEMORY" : "TRAIL MEMORY OFF"}</small><b>{memoryEnabled ? "What I know about you" : "Using this trip only"}</b></span><em>{memoryEnabled ? "2 TRIPS" : "OFF"}</em></header>{memoryEnabled && <div><span>Local over generic</span><span>Useful over decorative</span><span>Hands-free when possible</span></div>}<p>{memoryEnabled ? "Trail uses approved patterns to rank gifts and handling. You still control every route and transfer." : "Past trips are preserved, but their preferences do not affect recommendations."}</p><footer>{memoryEnabled && <button onClick={() => { setExpandedTrip("tokyo"); notify("Tokyo source opened below"); }}>Edit sources</button>}<button onClick={() => { setMemoryEnabled(!memoryEnabled); notify(memoryEnabled ? "Travel memory turned off" : "Travel memory enabled"); }}>{memoryEnabled ? "Forget memory" : "Enable memory"}</button></footer></section><div className="profile-section-label"><b>Current trip</b><span>Where stores and bags should connect</span></div>
      <section className="profile-form"><div className="date-pair destination-pair"><label><small>COUNTRY</small><input value={trip.country} onChange={(e) => updateTrip("country", e.target.value)} /></label><label><small>CITY</small><input value={trip.city} onChange={(e) => updateTrip("city", e.target.value)} /></label></div><div className="date-pair"><label><small>ARRIVE</small><input type="date" value={trip.startDate} onChange={(e) => updateTrip("startDate", e.target.value)} /></label><label><small>LEAVE</small><input type="date" value={trip.endDate} onChange={(e) => updateTrip("endDate", e.target.value)} /></label></div><label><span><small>HOTEL</small><input value={trip.hotel} onChange={(e) => updateTrip("hotel", e.target.value)} /></span><i>H</i></label><label><span><small>HOTEL ADDRESS</small><input value={trip.hotelAddress} onChange={(e) => updateTrip("hotelAddress", e.target.value)} /></span><i>⌂</i></label><label><span><small>TRAVELING WITH</small><input value={trip.companions} onChange={(e) => updateTrip("companions", e.target.value)} /></span><i>◎</i></label><label><span><small>SHOPPING TIME</small><select value={trip.freeTime} onChange={(e) => updateTrip("freeTime", e.target.value)}><option>1 hour</option><option>2 hours</option><option>3 hours</option><option>Half day</option><option>Full day</option></select></span><i>⌄</i></label></section>
      <section className="area-planner"><header><span><small>AREAS I’LL VISIT</small><b>Match stores to my itinerary</b></span><strong>{trip.areas.length}</strong></header><div className="area-chips">{trip.areas.map((area) => <button key={area} onClick={() => { updateTrip("areas", trip.areas.filter((item) => item !== area)); notify(`${area} removed`); }}>{area}<i>×</i></button>)}</div><form onSubmit={(event) => { event.preventDefault(); addArea(); }}><input value={areaDraft} onChange={(event) => setAreaDraft(event.target.value)} placeholder="Add a neighborhood or area…" aria-label="Area to visit" /><button type="submit" disabled={!areaDraft.trim()}>＋ Add</button></form><p>Trail places stores along these areas and carries purchases to your saved hotel.</p></section><div className="profile-link"><i>▣</i><span><b>Route and hotel connected</b><small>Stores around {trip.areas.join(", ")} → bag transfer to {trip.hotel}.</small></span></div><a className="workflow-link" href="/workflow" target="_blank" rel="noreferrer"><i>⌁</i><span><b>Open product workflow</b><small>Figma-ready mobile wireframes and state branches</small></span><em>→</em></a>
      <div className="profile-section-label history-label"><b>Past trips</b><span>{pastTrips.length} trips remembered</span></div><section className="trip-history">{pastTrips.map((item) => <article className={expandedTrip === item.id ? "expanded" : ""} key={item.id}><button onClick={() => setExpandedTrip(expandedTrip === item.id ? null : item.id)}><i className={item.color}>{item.city.charAt(0)}</i><span><small>{item.dates}</small><b>{item.city}, {item.country}</b><em>{item.purchases}</em></span><strong>CAD ${item.spend}</strong><b>{expandedTrip === item.id ? "⌃" : "⌄"}</b></button>{expandedTrip === item.id && <div><div>{item.areas.map((area) => <span key={area}>{area}</span>)}</div><p><i>✦</i>{item.insight}</p><button onClick={() => { setMemoryEnabled(true); updatePlan("preference", item.id === "tokyo" ? "Practical and useful" : "Thoughtful and useful"); setMessages((current) => [...current, { role: "ai", text: `${item.city} taste applied: ${item.insight}` }]); notify(`${item.city} taste applied to the current brief`); go("chat"); }}>Use this taste now →</button></div>}</article>)}</section><button className="main-button" onClick={() => { saveDeviceState(); go("home"); }}><span>Save trip profile<small>Save itinerary and progress on this device</small></span><i>✓</i></button>
    </div>}

    {toast && <div className="app-toast" role="status">{toast}</div>}<nav className={screen === "tracking" ? "tab-bar dark-tabs" : "tab-bar"}><button className={screen === "home" ? "active" : ""} onClick={() => go("home")}><i>⌂</i><span>Today</span></button><button className={screen === "chat" || screen === "review" ? "active" : ""} onClick={() => go("chat")}><i>✦</i><span>Ask</span></button><button className={screen === "picks" || screen === "shop" ? "active" : ""} onClick={shopDestination}><i>⌁</i><span>Shop</span></button><button className={screen === "drop" || screen === "pay" || screen === "tracking" ? "active" : ""} onClick={bagsDestination}><i>▣</i><span>Bags</span></button><button className={screen === "profile" ? "active" : ""} onClick={() => go("profile")}><i>◎</i><span>Trips</span></button></nav><div className="home-indicator" />
  </section></main>;
}
