/* eslint-disable @next/next/no-html-link-for-pages -- standalone anchor keeps the Figma HTML capture independent of Next navigation runtime */
import "./workflow.css";

type Frame = { id: string; phase: string; title: string; state: string; entry: string; exit: string; blocks: Array<{ kind?: "hero" | "row" | "button" | "note" | "choice"; text: string }> };

const frames: Frame[] = [
  { id: "01", phase: "DISCOVER", title: "Today", state: "No brief", entry: "Active trip", exit: "Start Ask", blocks: [{ kind: "hero", text: "Toronto · Day 2\nShop local. Keep your hands free." }, { kind: "row", text: "Today’s areas · 3h free · CAD 180" }, { kind: "button", text: "Plan a hands-free route" }, { kind: "note", text: "State variants: route ready / shopping / bags active" }] },
  { id: "02", phase: "DISCOVER", title: "Ask Trail", state: "Collecting", entry: "User intent", exit: "Review brief", blocks: [{ kind: "row", text: "Approved memory · Toronto · 3 areas" }, { kind: "hero", text: "AI conversation\nWho? What? Budget? Route? Handling?" }, { kind: "choice", text: "Quick replies · reference photo" }, { kind: "button", text: "Review shopping brief" }] },
  { id: "03", phase: "PLAN", title: "Shopping brief", state: "Draft", entry: "AI summary", exit: "Generate route", blocks: [{ kind: "row", text: "Recipient · quantity · gift type" }, { kind: "row", text: "Gift budget · route areas · time" }, { kind: "row", text: "Heavy · fragile · chilled · hotel" }, { kind: "button", text: "Find stores along today’s route" }, { kind: "note", text: "If edited after approval → route needs refresh" }] },
  { id: "04", phase: "PLAN", title: "Route & stores", state: "Route ready", entry: "Approved brief", exit: "Start shopping", blocks: [{ kind: "hero", text: "YOU ─ Store 1 ─ Store 2 ─ HOTEL\n+13 min detour" }, { kind: "row", text: "Look for · expected price · store · hours" }, { kind: "choice", text: "Save · Directions · Call · Replace" }, { kind: "button", text: "Start in-store route" }, { kind: "note", text: "Sample data clearly labeled" }] },
  { id: "05", phase: "SHOP", title: "Shop in store", state: "At stop", entry: "Route started", exit: "Record outcome", blocks: [{ kind: "row", text: "1/3 stops · CAD 118 left" }, { kind: "hero", text: "Spacing Store\nLook for Ontario stoneware" }, { kind: "choice", text: "Bought · Not found · Skip" }, { kind: "row", text: "Next stop · 7 min walk" }] },
  { id: "06", phase: "SHOP", title: "Purchase sheet", state: "Editing", entry: "Bought tapped", exit: "Confirmed purchase", blocks: [{ kind: "row", text: "Total paid · tax included" }, { kind: "row", text: "Quantity · bags · recipient" }, { kind: "choice", text: "Standard · Heavy · Fragile · Chilled" }, { kind: "row", text: "Budget after saving" }, { kind: "button", text: "Save purchase" }, { kind: "note", text: "Cancel = no purchase state" }] },
  { id: "07", phase: "SHOP", title: "Alternative", state: "Not found", entry: "Unavailable", exit: "Replace stop", blocks: [{ kind: "hero", text: "Not found at this store" }, { kind: "row", text: "Nearby · same area · same budget" }, { kind: "row", text: "Alternative store · +3 min" }, { kind: "button", text: "Replace this stop" }, { kind: "choice", text: "Keep searching · Skip" }] },
  { id: "08", phase: "TRANSFER", title: "Purchased bags", state: "Select", entry: "≥1 purchase", exit: "Eligibility check", blocks: [{ kind: "hero", text: "5 hours left outside\nChoose bags for the hotel" }, { kind: "choice", text: "☑ Ceramics · Fragile" }, { kind: "choice", text: "☑ Chocolate · Chilled" }, { kind: "choice", text: "☐ Tote · Standard" }, { kind: "button", text: "Check transfer options" }] },
  { id: "09", phase: "TRANSFER", title: "Transfer check", state: "Eligible", entry: "Selected bags", exit: "Confirm transfer", blocks: [{ kind: "row", text: "Fragile packing · seal photo" }, { kind: "row", text: "Ice pack · safe-until window" }, { kind: "row", text: "Hotel acceptance · arrival window" }, { kind: "hero", text: "2 bags · estimated CAD 12" }, { kind: "button", text: "Confirm hotel bag transfer" }, { kind: "note", text: "Ineligible → reason + carry/storage alternative" }] },
  { id: "10", phase: "TRANSFER", title: "Partner handoff", state: "Sealed", entry: "Transfer confirmed", exit: "Driver collected", blocks: [{ kind: "hero", text: "BAG PASS · TR–2718\n▥ ▥▥ ▥ ▥▥▥" }, { kind: "row", text: "Bag IDs · count · handling" }, { kind: "row", text: "Partner checks every seal" }, { kind: "button", text: "Bags handed to partner" }] },
  { id: "11", phase: "COMPLETE", title: "Bag tracking", state: "Active", entry: "Partner handoff", exit: "Hotel receipt", blocks: [{ kind: "hero", text: "Your hands are free." }, { kind: "row", text: "Sealed → Collected → On route → Hotel" }, { kind: "row", text: "Driver · sample ETA · chilled status" }, { kind: "choice", text: "Report delay · seal issue" }, { kind: "button", text: "Preview hotel receipt" }] },
  { id: "12", phase: "COMPLETE", title: "Hotel receipt", state: "Received", entry: "Hotel handoff", exit: "Today + trip memory", blocks: [{ kind: "hero", text: "Received by The Annex Hotel\nFront desk · 6:42 PM" }, { kind: "row", text: "Bag count · seal status · handling" }, { kind: "row", text: "Purchases · actual spend · transfer fee" }, { kind: "choice", text: "Save receipt · Report issue" }, { kind: "button", text: "Done — continue my trip" }] },
];

export default function WorkflowPage() {
  return <main className="wf-board">
    <header className="wf-header"><div><span className="wf-brand">T</span><p>TRAIL · PRODUCT WORKFLOW WIREFRAME</p><h1>Shop locally.<br />Travel hands-free.</h1></div><div className="wf-actions">{/* Standalone capture page intentionally avoids Next runtime navigation. */}<a href="/">Open prototype</a><span>390 × 844 mobile frames · Figma capture ready</span></div></header>
    <section className="wf-principles"><div><b>Product boundary</b><span>User buys in store. TRAIL recommends the route and transfers purchased bags.</span></div><div><b>Primary loop</b><span>Ask → Brief → Route → Shop → Purchase → Bags → Hotel</span></div><div><b>Truth rule</b><span>External inventory, maps and transfer events stay labeled Sample or Simulated.</span></div></section>
    <section className="wf-legend"><span><i className="navy" />Primary user action</span><span><i className="lime" />AI generated or refreshed</span><span><i className="orange" />Conditional approval</span><span><i className="red" />Error and recovery</span></section>
    <section className="wf-flowline"><b>ACTIVE TRIP</b><span>ASK</span><span>PLAN ROUTE</span><span>BUY IN STORE</span><span>SELECT BAGS</span><span>HOTEL RECEIPT</span></section>
    <section className="wf-frames">{frames.map((frame, index) => <article className="wf-card" key={frame.id}><div className="wf-card-meta"><span>{frame.phase} / {frame.id}</span><em>{frame.state}</em></div><div className="wf-phone"><header><i /><b>{frame.title}</b><i /></header><section>{frame.blocks.map((block, blockIndex) => <div className={`wf-block ${block.kind ?? "row"}`} key={`${frame.id}-${blockIndex}`}>{block.text.split("\n").map((line) => <span key={line}>{line}</span>)}</div>)}</section><footer><i /><i /><i /><i /><i /></footer></div><div className="wf-annotation"><p><b>ENTRY</b>{frame.entry}</p><p><b>PRIMARY</b>{frame.blocks.find((block) => block.kind === "button")?.text}</p><p><b>EXIT</b>{frame.exit}</p><p><b>PERSIST</b>{index < 4 ? "Trip · brief · route" : index < 8 ? "Visit · purchase · budget" : "Bag · custody · receipt"}</p></div>{index < frames.length - 1 && <div className="wf-connector">→</div>}</article>)}</section>
    <section className="wf-branches"><h2>Required state branches</h2><div><article><b>Recommendation unavailable</b><span>Search nearby → replace stop → preserve recipient and budget</span></article><article><b>Actual price exceeds plan</b><span>Show overage → approve rebalance or edit the brief</span></article><article><b>Transfer ineligible</b><span>Explain why → carry, storage, or different bag option</span></article><article><b>Hotel handoff fails</b><span>Delay/decline → support path → custody remains visible</span></article></div></section>
  </main>;
}
